### ISSUE TITLE
Task description in task details does not respect formating outside of task description editor.

### ISSUE THREAD

**Issue by cfsnkajok** [coolfiresolutions/core-service-desk#18]
**Imported from Jira Service Desk**<br>Reporter Nick Kajok on Oct/14/20 5:00 PM<br><br>**Describe the improvement or new feature you would like to see**<br>I created a task description with multiple lines. This task description formats correctly when editing the task description but when viewing the description in the task detail view, the description is no longer multiline. The description is still multiline when I go back to edit this description, just not in the task view. See attachments.

[~accountid:557058:38c6316c-e7a9-431f-a5c3-a1ad63bd5455]<br><br>**Where would you like to see this improvement or feature request?**<br><br><br>

**Comment by MelissaEaster** [comment]
@cfsnkajok I am not seeing this on web for corp or dev nor am I seeing this on iOS.  Where did you see it and what were you using?

**Comment by cfsnkajok** [comment]
It is on Web.

Steps to reproduce:
1. Log into web app.
2. Navigate to task kanban
3. Create a new task.
4. Edit description field and enter multiple lines of text using the enter key to separate the lines.
5. Click Save on the description field.

Expected Result: The task description appears multiline in the task view.
Actual Result: The task description has been condensed to a single line.

**Comment by MelissaEaster** [comment]
@cfsnkajok I am unable to produce this issue in dev or prod with the above steps.

**Comment by cfsnkajok** [comment]
I was able to reproduce yesterday in the prod environment so maybe we can meet up next week and I can try to reproduce it live.

**Comment by MelissaEaster** [comment]
Yes please 😀

Sent from my iPhone

> On Feb 19, 2021, at 9:51 PM, Nicholas Kajok <notifications@github.com> wrote:
> 
> ﻿
> I was able to reproduce yesterday in the prod environment so maybe we can meet up next week and I can try to reproduce it live.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
_*STATEMENT OF CONFIDENTIALITY:* This Email is covered by the Electronic 
Communications Privacy Act, 18 U.S.C. §§2510-2521 and is legally 
privileged. The information contained in this electronic message and any 
attachments thereto are intended for the exclusive use of the addressees 
and may contain confidential and/or privileged information. If you are not 
the intended recipient, please inform the sender immediately via telephone, 
fax or reply e-mail and delete all copies of this message and all 
attachments from your system._

**Comment by cfsnkajok** [comment]
@MelissaEaster , I didn't have a chance to demo this to you, but I believe this will be resolved with improvements in progress to the Task description editor.

**Comment by MelissaEaster** [comment]
Thanks Nick. 

Sent from my iPhone

> On Feb 24, 2021, at 4:56 PM, Nicholas Kajok <notifications@github.com> wrote:
> 
> ﻿
> @MelissaEaster , I didn't have a chance to demo this to you, but I believe this will be resolved with improvements in progress to the Task description editor.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
_*STATEMENT OF CONFIDENTIALITY:* This Email is covered by the Electronic 
Communications Privacy Act, 18 U.S.C. §§2510-2521 and is legally 
privileged. The information contained in this electronic message and any 
attachments thereto are intended for the exclusive use of the addressees 
and may contain confidential and/or privileged information. If you are not 
the intended recipient, please inform the sender immediately via telephone, 
fax or reply e-mail and delete all copies of this message and all 
attachments from your system._
