### ISSUE TITLE
Add paragraph formatting to the Session description without using html in edit screen

### ISSUE THREAD

**Issue by cfsnkajok** [coolfiresolutions/core-service-desk#33]
**Imported from Jira Service Desk**<br>Reporter tfabrizio@coolfiresoltuions.com on Jan/05/21 11:10 AM<br><br>**Describe the improvement or new feature you would like to see**<br>When adding a session description when creating or editing a session you can format information with simple html line breaks and such but it would be better if the line breaks transferred over to the saved session automatically. It's easier to read the information and users in the field won't typically know how to format in html.<br><br>**Where would you like to see this improvement or feature request?**<br>All Core Apps/API or Unknown<br><br>

**Comment by cfsadellamano** [comment]
Fixed by: coolfiresolutions/core-web#24

(enables WYSIWYG editor for Session description)
