### ISSUE TITLE
Create Password Issues

### ISSUE THREAD

**Issue by gtrexler** [coolfiresolutions/core-service-desk#39]
**Describe the bug**
Capturing a few Create Password issues from earlier today per Nick.

**Where are you seeing this?**
ex: Web, Admin, Signup, Android, iOS, Multiple Apps
Sign-up

**To Reproduce**
Proceed through Sign-up to Create Password
1. Enter Password without a digit, with spaces, ... All dots turn green. But you receive "Error: Please ensure your password matches all requirements"
2. Enter Confirm Password that does not match Password. Hit Continue. Error message is on top of password requirements.
3. On Safari, enter Confirm Password that does not match Password. Only see error message while holding down mouse. Don't see error message at all on phone. Tab order seems to be off, skipping Continue button.

**Expected behavior**
1. Indication of why password is invalid.
2. Ideally do not display simultaneously or better spacing.
3. Work as with Chrome.

**Screenshots**
2. ![image](https://user-images.githubusercontent.com/78811840/108046397-2d7bbd00-700a-11eb-8ca1-0bb8038f07a8.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stramel** [comment]
This has been addressed in the web already. https://github.com/coolfiresolutions/core-web/pull/77 and is set to be released in the next release.

**Comment by stramel** [comment]
I believe this is good to close @cfsnkajok

**Comment by cfsnkajok** [comment]
@gtrexler, this issue is now resolved and deployed to the field. Please re-test and let us know if you continue to see the issue.
