### ISSUE TITLE
Chat msg & Image error

### ISSUE THREAD

**Issue by MarkRogersCoolfire** [coolfiresolutions/core-service-desk#40]
Typed a chat message on iphone app, then attached JPG. Clicking send, only the image transmitted and the text was lost.

ios 14.4

**Comment by MelissaEaster** [comment]
Here is a video of the behavior 
Tested on dev
iOS Xs

https://user-images.githubusercontent.com/77986375/108421385-bce7c280-71fa-11eb-92a8-042bf15680cc.MP4

**Comment by cfsbhawkins** [comment]
Tracked by internal bug https://github.com/coolfiresolutions/core-ios/issues/56

**Comment by cfsbhawkins** [comment]
Issue to be resolved in 1.7.0
