### ISSUE TITLE
Checking driver route causes crash - Ready Set

### ISSUE THREAD

**Issue by toberting** [coolfiresolutions/core-service-desk#43]
**Describe the bug**
When Ready Set is using mobile or desktop, select a delivery session then click on the "driver route" on left hand side, you see a snapshot of the driver on a map.  When you try to go back to the previous screen, Core crashes.  You have to then close the app and restart it.

**Where are you seeing this?**
ex: Web, Admin, Signup, Android, iOS, Multiple Apps
mobile and desktop

**To Reproduce**
1. Open Session
2. Expand the Details, "Routing and Tracking"
3. Click link to "Order Route"
4. Click the back button
5. Core crashes
6. It isn't all the time, but I have replicated it

**Expected behavior**
We should be able to click the Driver Route link, see where the driver is (it would be nice if it was live vs just a snapshot) and then toggle back to the session without crashing Core.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: PC
 - Browser Chrome
 - Version 88.0.4324.190

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS
 - Browser Safari and Google

**Additional context**

**Comment by cfsbhawkins** [comment]
@m-amarillas I think this is yours?

**Comment by m-amarillas** [comment]
Hey Thomas, this is a ReadySet specific issue, so we can close this official product ticket and discuss this through our own project definition plan for them specifically. I'll see if I can reproduce and get a fix in place shortly.

Thanks for reporting!

**Comment by cfsnkajok** [comment]
Marking this closed per Marc.
