### ISSUE TITLE
Unable to ReInvite Inactive User With No Cognito Username

### ISSUE THREAD

**Issue by m-amarillas** [coolfiresolutions/core-service-desk#45]
**Describe the bug**
We have a few users for American Expediting who were "deleted" before they converted to Cognito. Now, they want to re-invite them into the system, but when they try to send a new invitation, it does not reactivate that account. Instead, it sends a new invitation to that person, and when they try to re-signup, it errors due to duplicate emails.

If possible, we could just hard delete the old user accounts from the database. 

**Where are you seeing this?**
Web App

**To Reproduce**
1. Have a user with no Cognito Username
2. Delete that user so they have an inactive role
3. Try to send an invite to that same email address

**Expected behavior**
We would want that user to be active in the system again.

**Screenshots**

**Desktop (please complete the following information):**
- Chrome

**Comment by cfsnkajok** [comment]
@m-amarillas , I'll talk with @cfsdbarnes to see what the recommended course of action here is.

**Comment by cfsdbarnes** [comment]
@m-amarillas send me the email addresses affected and I'll fix them.

**Comment by m-amarillas** [comment]
We are good now. You can reactivate a user via GraphQL if it's absolutely needed. I was able to work to get these individuals reactivated. Thanks.
