### ISSUE TITLE
ReadySet Workspace Going Down Consistently 

### ISSUE THREAD

**Issue by m-amarillas** [coolfiresolutions/core-service-desk#46]
**Describe the bug**
ReadySet has reported that their workspace keeps going down as they monitor driver positioning and session activity. I looked at some of the error logs and see that there was a 502 error as their drivers started doing their drives.

**Where are you seeing this?**
Web App

**To Reproduce**
Not sure, They say it's happening randomly. On the Node Red side of things, we are PATCHing the Session when the driver says they have arrived at their location so that the session location reflects the correct next stop. Not sure why a PATCH would crash the server though. 

**Screenshots**
![Image from iOS (1)](https://user-images.githubusercontent.com/53492670/109342426-7533ed00-7831-11eb-897b-53163828c637.jpg)
![Image from iOS](https://user-images.githubusercontent.com/53492670/109342430-75cc8380-7831-11eb-8cd9-380558940110.jpg)

**Desktop (please complete the following information):**
 - Chrome

**Comment by cfsdbarnes** [comment]
@m-amarillas I have upgraded this instance to a higher scalability configuration.  Let me know if the issue persists.
