### ISSUE TITLE
Sort feature on Sessions Dashboard

### ISSUE THREAD

**Issue by Jabdullah81** [coolfiresolutions/core-service-desk#47]
**Describe the bug**
When selecting the sort by date feature on the session dashboard whether you choose start or end date, it will always sort from furthest away date to newest.  I would like to see if we can reverse that sort to have the dates start with the newest date as this is a request from a customer (Ard). 

**Where are you seeing this?**
Session Dashboard on web and mobile

**To Reproduce**

**Expected behavior**
I would like to see if we can reverse that sort to have the dates start with the newest date as this is a request from a customer (Ard). 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cfsnkajok** [comment]
@Jabdullah81, we've heard something similar from other customers. We've actually added the ability to sort any of the session lists by ascending or descending order. This should provide the functionality you're customer is hoping for. This is scheduled for release this week.

**Comment by cfsnkajok** [comment]
@Jabdullah81 , this feature has now been released to the field. You can find the Session Sorting in list header on the Sessions list view. It appears as an Up and Down arrow next to each other.
<img width="180" alt="Screen Shot 2021-03-11 at 5 02 09 PM" src="https://user-images.githubusercontent.com/10697609/110866921-89450900-828b-11eb-89ec-2fcb2428cc00.png">
