### ISSUE TITLE
Users Not Receiving Forgot Password Email

### ISSUE THREAD

**Issue by m-amarillas** [coolfiresolutions/core-service-desk#67]
**Describe the bug**
I am receiving weekly (sometimes daily) support requests to help with password resets. The most common complaint is that people do not receive their password reset email. I originally thought that it might have gone to their spam or they just were not doing it correctly, but I have heard from 7 different people over the last two weeks that this is an issue.

I know that it will be tricky to dig into this one since it seemingly is working as expected, so please let me know how I can help.

**Where are you seeing this?**
Web

**To Reproduce**
1. Begin the forgot your password process
2. enter your email address
3. Some users are reporting that they never receive a password reset email

**Expected behavior**
To receive the email

**Desktop (please complete the following information):**
The most recent user was in Chrome v89.0.4389

**Comment by cfsnkajok** [comment]
@m-amarillas , thanks for reporting this, we'll investigate asap.

**Comment by cfsbhawkins** [comment]
I just looked in the AWS bounce queue. I have a few rejections looks like people are entering bad emails. Since this is public I will not share them here.

**Comment by cfsbhawkins** [comment]
Check slack for notes

**Comment by cfsnkajok** [comment]
Posting update here from slack, Brian found one matching email in the bounce list that was supposed to be a valid email. Marc supplied another email that was not in the bounce list, but might appear in the bounce list, as these get queued up by Amazon before they are shared with us for review. Brian will review the bounce list tomorrow and we will discuss possible next steps tomorrow.

**Comment by cfsbhawkins** [comment]
Since adding DKIM support to the AWS SES, there have been zero bounces this week. Closing.

**Comment by cfsnkajok** [comment]
Thanks for taking care of this @cfsbhawkins . @m-amarillas will you please let us know if you see or hear of any more cases of users not receiving password reset emails? Thank you.

**Comment by m-amarillas** [comment]
Hi Team,

I'm still receiving support requests on a weekly basis. @cfsbhawkins I'm slacking you a list of emails to see if they were rejected.
