### ISSUE TITLE
Description Hyperlinks are not working on Android Phones

### ISSUE THREAD

**Issue by m-amarillas** [coolfiresolutions/core-service-desk#68]
**Describe the bug**
Description Hyperlinks are not working on Android Phone. This has been reported by several American Expediting drivers and I can reproduce on my Android Phone.

**Where are you seeing this?**
Android in Sessions and Tasks

**To Reproduce**
1. Create a Session and/or Task
2. Add a hyperlink in the description
3. Try to click the hyperlink on the phone

**Screenshots**
![image000000](https://user-images.githubusercontent.com/53492670/113353897-f3d5eb80-9303-11eb-8f1c-80b8f42a9f32.png)

**Smartphone (please complete the following information):**
- Android Pixel 3a XL (Android Version 10)

**Comment by cfsnkajok** [comment]
Marc, thanks for your report. I have passed this onto the Android team for review.

**Comment by cfsbhawkins** [comment]
Can you provide sample HTML? From our testing this does work.

**Comment by m-amarillas** [comment]
Here's the HTML from the task in the screenshot. This was generated from the WYSIWYG

<p>Complete all tasks in the attached form</p><p></p><p><a href=\"https://www.google.com\">This is a link</a></p>

**Comment by m-amarillas** [comment]
`<p>Complete all tasks in the attached form</p><p></p><p><a href=\"https://www.google.com\">This is a link</a></p>`

**Comment by cfsbhawkins** [comment]
Ok we have opened a PR to the library we use, Android only supports HTML or Linkify (as its called when you want it to auto detect, phone, email, or websites in text) We have updated the library to work and support both, at this time we are waiting for them to accept the PR and make a release. (They had a logged bug for this exact issue). We do have a hacked in approach on dev that works but I would assume the project owner will accept this PR in the next week or so.

**Comment by cfsnkajok** [comment]
@cfsbhawkins , this is released now right?

**Comment by cfsbhawkins** [comment]
No will go out in next batch of updates.

**Comment by cfsnkajok** [comment]
Okay thanks for the update.

**Comment by cfsbhawkins** [comment]
Fixed 1.7.0, started production rollout.
