### ISSUE TITLE
Unable to Download App on HUAWEI VOG-L29 Device

### ISSUE THREAD

**Issue by m-amarillas** [coolfiresolutions/core-service-desk#70]
**Describe the bug**
I just received a phone call from American Expediting saying they have a driver who cannot download the Coolfire Core app. This rep was pretty technical and said that he tried restarting the phone, clearing cache, and allowing untrusted sources, but he could not get the app to download.

He is saying that when they click download, it says "pending" but then does not progress any further.

I was curious if the Android team has seen this happen and if there are any suggestions on resolution.

**Where are you seeing this?**
Mobile Android App

**To Reproduce**
Not sure how to reproduce

**Smartphone (please complete the following information):**
HUAWEI VOG-L29 Device

**Comment by cfsbhawkins** [comment]
Marc, 

Our app is only delivered by Google Play. We do not support any third party sources. He should contact his device manufacture or Google to investigate if it's a supported device or not, Im seeing mixed remarks if its a supported device as it depends which market it was intended for.

Brian

**Comment by cfsbhawkins** [comment]
See for details, but seems like Google Play might be hacked on this device, using non official ways. Not sure, basically Google is not allowed to play with Hauwei due to the ban on them in the US.

https://www.theverge.com/2019/9/6/20852461/huawei-p30-pro-design-update-android-10-ifa-2019

**Comment by cfsnkajok** [comment]
@m-amarillas , following on with what Brian stated, do we know if this user has any other issues using apps from the google play store on this device? If what Brian is indicating is true, it might be difficult to provide a workaround for this user, as the app could be failing to install in a way that is outside of our control.

**Comment by m-amarillas** [comment]
Hey All,

I spoke with the rep again today and apparently the app decided to download last night. They said nothing was done, it just randomly started working. I wish I had more insight.

We can close this out. Thanks for your research though, it'll be helpful if we see this again for this type of device.

Marc

**Comment by cfsbhawkins** [comment]
Things to look out for with his device would be push notifications and if they work or not.  Just as a note going forward.
