### ISSUE TITLE
Loading Spinner After Selecting User During Task Assignment.

### ISSUE THREAD

**Issue by cfsnkajok** [coolfiresolutions/core-service-desk#72]
**Describe the bug**
On Web, when I open a Task detail view and attempt to assign an issue to a user, there is a loading spinner that appears next to the name I have selected. This loading spinner is visible after I've selected this user and will spin infinitely. The spinner doesn't appear to have any impact on the assignment of the user, as when I click out of the Task Details the selected user is populated (even though it was still spinning when I clicked the X).

**Where are you seeing this?**
Web

**To Reproduce**
1. Go to Web, Task Kanban Board
2. Click on a Task to open details
3. Click 'Assign To'.
4. Select a User.

User selected appears as selected, but with a loading spinner to their name.

**Expected behavior**
User should appear as selected without a spinner next to their name.

**Screenshots**
![Screen Shot 2021-04-09 at 10.51.18 AM.png](https://images.zenhubusercontent.com/60352835c5aeef1899bd305d/d87babcd-1578-40e1-8418-e90ed3111cfe)

**Desktop (please complete the following information):**
Chrome Browser

**Comment by cfsnkajok** [comment]
Found by @gtrexler.

**Comment by cfsadellamano** [comment]
Fixed in 2.6.0

**Comment by cfsnkajok** [comment]
Awesome!
