### ISSUE TITLE
Unable to Add Tasks to Session Types

### ISSUE THREAD

**Issue by m-amarillas** [coolfiresolutions/core-service-desk#73]
**Describe the bug**
When I try to add tasks to session types, I get a "Cannot POST /core/api/v1/sessionTypes/6d97dfb9-cfee-43d9-bee9-aeda5320cf76/tasks" error. I think we removed that route in the latest release.

**Where are you seeing this?**
Admin - ReadySet

**To Reproduce**
1. Create New Session Type
2. Try to Add Tasks

**Screenshots**
![Screen Shot 2021-04-09 at 3 00 02 PM](https://user-images.githubusercontent.com/53492670/114234640-a7faf600-9944-11eb-98a7-d4d8630783c4.png)
![Screen Shot 2021-04-09 at 3 00 12 PM](https://user-images.githubusercontent.com/53492670/114234652-acbfaa00-9944-11eb-9d49-1bdd21cbe5e5.png)

**Desktop (please complete the following information):**
 - Chrome

**Comment by cfsnkajok** [comment]
Looks like we missed this call when cleaning up POST calls. @cfsadellamano

**Comment by cfsnkajok** [comment]
Let's target this for a hotfix.

**Comment by cfsadellamano** [comment]
Fixed in 1.3.2
