### ISSUE TITLE
Session Search in iOS Not Working

### ISSUE THREAD

**Issue by aeversgerd** [coolfiresolutions/core-service-desk#76]
**Describe the bug**
Search for Sessions on the Sessions screen on the iOS app returns inaccurate results 

**Where are you seeing this?**
iOS

**To Reproduce**
1. Go to Sessions screen on iOS
2. Click on Search function 
3. Search for anything (I was looking for 4th Bin)
4. Returns inaccurate/irrelevant results 

**Expected behavior**
Search feature works the same way the home screen search works 

**Screenshots**
![image](https://user-images.githubusercontent.com/75394982/114596479-52309180-9c55-11eb-8bae-a4ba1ca0caf3.png)

**Desktop (please complete the following information):**
iOS 1.7.0

**Smartphone (please complete the following information):**
iPhone X

**Comment by cfsnkajok** [comment]
I was able to reproduce this on iOS. Search works fine from Home/Dashboard, does not appear to return any results in Sessions list.

@cfsbhawkins , @cfsbzeidler

**Comment by cfsnkajok** [comment]
This has been replicated and escalated in priority.

**Comment by cfsnkajok** [comment]
This is now resolved and released to production.
