### ISSUE TITLE
App frozen on blue splash screen

### ISSUE THREAD

**Issue by JohnPBaker** [coolfiresolutions/core-service-desk#78]
**Describe the bug**
App stuck on blue splash screen. Never loads anything else. Doesn't time out. No error message

**Where are you seeing this?**
Android

**To Reproduce**
1. Launch app

**Screenshots**
![image](https://user-images.githubusercontent.com/77636852/114927671-57c5dd00-9df7-11eb-970c-1d663f229fbe.png)

**Smartphone (please complete the following information):**
 - Pixel 4XL
 - Android version 11
 - Coolfire Core (Beta)

**Comment by cfsbhawkins** [comment]
I saw this issue yesterday too, Cognito had a hiccup and did not update my token, clearing app data fixed it as I could relogin.

**Comment by cfsnkajok** [comment]
@cfsbhawkins is this for beta app only, or would any users in production see this?

**Comment by cfsbhawkins** [comment]
It would be in production too, current beta app = production app.  Looking at our network metrics looks like AWS has had a few issues a few days back and it has started to go back up. Yesterday I updated the AWS SDK as they had a patch out for their cognito stuff where logins could fail. 

Calls specifically to Cognito:
<img width="335" alt="Screen Shot 2021-04-16 at 2 44 19 PM" src="https://user-images.githubusercontent.com/14224435/115076548-53b2c180-9ec2-11eb-9c95-a12227d7ae75.png">

**Comment by cfsbhawkins** [comment]
I will monitor the logs and if we see another dip, may need to check in with Amazon.

**Comment by cfsnkajok** [comment]
Brian, please keep a very very close eye on this. If the response rate from cognito is averaging only 95% with what looks like dips into the high 70s, that is, frankly, terrible. I think we should get a ticket opened with Amazon now and monitor closely. If the situation doesn't improve in the next few days we will need to look at taking serious action (i.e. moving providers).

For visibility: @cfsadellamano , @cfsdbarnes

**Comment by cfsnkajok** [comment]
Team will be meeting Tuesday to discuss potential cause/fix.

**Comment by cfsbhawkins** [comment]
API is rolling a caching fix. I have also added a progress spinner to make it not feel locked up, as it will eventually login once the AWS calls succeed in refreshing the token.

**Comment by cfsnkajok** [comment]
Good to hear. Thanks for the update.

**Comment by cfsbhawkins** [comment]
Added a progress spinner fixed 1.7.0, started production rollout.
