### ISSUE TITLE
Cannot See Session Details from Push Notification

### ISSUE THREAD

**Issue by m-amarillas** [coolfiresolutions/core-service-desk#79]
**Is your improvement or feature request related to a problem? Please describe.**
When users receive a notification, it takes them into the Latest Updates feed of the Session. From there, the user cannot easy navigate to the Session Details or Session Tasking. When clicking the "back" button, it takes them to the homescreen, where they have to try and find their way back to the Session.

**Where would you like to see this improvement or feature request?**
Mobile Apps

**Describe the solution you'd like**
An easier way to see the Session information when clicking into a push notification.

**Describe alternatives you've considered**
If we have deep linking, I could use that potentially to take the user to exact location that they care about.

**Additional context**
Screenrecording attached below:

https://user-images.githubusercontent.com/53492670/115152247-f93a7200-a035-11eb-8211-3b092e39052a.MP4

**Comment by cfsbhawkins** [comment]
Marking as feature enhancement, the the push notification was a text update notification thus why it routed to the Text feed. Had it been a session update or something then it would have been routed to the session details.

**Comment by m-amarillas** [comment]
To clarify, I did click on the push notification that said the Task was marked as complete, but it still brought me to the Latest Updates feed. 

I agree it's not necessarily a bug, but I want to make sure the use case was clearly understood. Reach out if there are further questions. Thanks!

**Comment by cfsbhawkins** [comment]
This is because of how the system generated status updates are just text messages, they are no different than if you and I were chatting.  Tasks status changes do not generate a push notification on their own, so instead the "target" is a conversation object, thats why it routes to the session conversation. (Tasks did not exist when push notifications were built)

**Comment by cfsnkajok** [comment]
@m-amarillas , thanks for submitting. We'll discuss what we can do to enhance this flow in the next design sync up. There is a decent level of effort to rework this, so we will need to assess the LOE and then funnel it through PMB to make a call on whether this makes it into the existing native apps, or if we table this and include it with the Flutter app.
==

**Comment by cfsbhawkins** [comment]
Updated to match android logic in 1.8.0, we just route to session details on any message related to a session or task, vs the convo.
