### ISSUE TITLE
AmEx Drivers Reporting Android App Stalling on Open

### ISSUE THREAD

**Issue by m-amarillas** [coolfiresolutions/core-service-desk#84]
**Describe the bug**
I have had two drivers report that their mobile app's open to the splash page, but doesn't go any further. I was able to get info for one of the driver, along with a screenshot. They're provided below.

Here's the link to their Pendo details: https://app.pendo.io/visitor/9dd1b5ac-c536-434c-9076-53e39df0c65c

**Where are you seeing this?**
Android Mobile App

**To Reproduce**
I cannot reproduce this on my android test phone

**Screenshots**
![Screen Shot 2021-04-19 at 4 15 02 PM](https://user-images.githubusercontent.com/53492670/115310550-93ccab00-a133-11eb-9bf0-40bd4d411c2e.png)
![Screenshot_20210419-140455_Core](https://user-images.githubusercontent.com/53492670/115310566-9cbd7c80-a133-11eb-90f6-187a7b76d55b.jpg)

**Smartphone (please complete the following information):**
 - Device - samsung SM-N950U
 - Version - 1.6.0

**Comment by cfsnkajok** [comment]
@m-amarillas thank for reporting, we're looking into something similar already. We'll keep you advised.

**Comment by cfsnkajok** [comment]
@cfsbhawkins, this looks to be the same as #78. Both times this has happened on Android devices. Coincidence? Or still related to Cognito potentially?

**Comment by cfsbhawkins** [comment]
Yes this is #78 we can track on that one, but I am seeing we have dropped down to 92% success today with Cognito. So does appear we are hitting service limits again. They should be able to try again in a few minutes, as long as it does not corrupt the internal refresh token, if not. Clearing App Storage and signing back in resolved it.

**Comment by cfsbhawkins** [comment]
API is in the process of reducing calls to Cognito, we will keep an eye once released to see if our success rates increase.

**Comment by cfsbhawkins** [comment]
Closing this to keep tracking in #78
