### ISSUE TITLE
Android - Background Location Tracking Not Working

### ISSUE THREAD

**Issue by m-amarillas** [coolfiresolutions/core-service-desk#85]
**Describe the bug**
I received reports that ReadySet drivers had their background location tracking enabled, bit were still not getting up to date locations. I was able to reproduce what's happening on my Pixel 3. Video attached.

I believe this was working fine prior to the last release 

**Where are you seeing this?**
Android app

**To Reproduce**
1. Login on your Android device
2. Enable background tracking
3. Put the app in the background 
4. See that location tracking turns off

**Expected behavior**
Location tracking continues until the app is shut off or you logout. This is how it functions on iPhone

**Screenshots**

https://user-images.githubusercontent.com/53492670/115338041-b1b40300-a167-11eb-8fcf-65f9267e1396.mp4

**Smartphone (please complete the following information):**
 - Pixel 3
 - 1.6.0

**Additional context**

**Comment by cfsbhawkins** [comment]
I will look into it, changes were made in 1.6 to resolve a crash on the background location.

**Comment by cfsbhawkins** [comment]
Not related to recent changes, but related to Android 11 and Googles decision to remove the known workaround. We will need to now jump through Googles hoops to get this approval to work again. So its not all users just ones using a newer android that would have this issue.

**Comment by m-amarillas** [comment]
Thanks Brian. I personally think we'll need to go through the process since it's a crucial part of these customer's setup. Looking at [Google's own article](https://developer.android.com/training/location/background) they call out that Geofencing is an approved reason for granting this permission, so I think we should be able to take that approach as it is a core feature of our app.

I'm open for discussion.

**Comment by cfsnkajok** [comment]
@cfsbhawkins , let's do what we can to update the app and resubmit to get background location updates working here again. Let me know if you think this will alter our plans/resources on Flutter or if this is something that will take relatively low effort.

**Comment by m-amarillas** [comment]
@cfsbhawkins If you need help with the video submission I can assist.

**Comment by cfsbhawkins** [comment]
No it will take me a day or 2 to get it in the current build, then maybe up to a week to get it in store. I will let you know when I submit it.

**Comment by cfsbhawkins** [comment]
@m-amarillas once we get approval you may want to record a video of the new process, there is a manual intervention the user must do to enable background locations. Basically just like the power manager the best I can do is take them to the location settings and they must manually select all the time when I request background location permission.  You may want to send updated directions.

**Comment by m-amarillas** [comment]
Is it more than going into their settings and enabling background location tracking? I already instruct them to do that. Here's one of my training videos:

https://youtu.be/Sjy6MpFso98

**Comment by cfsbhawkins** [comment]
Yes on Android there will be a bit more to enable it, I can only take them to the OS settings where they must grant All the time tracking.

**Comment by cfsbhawkins** [comment]
Currently update is under review by Google.

**Comment by cfsbhawkins** [comment]
Fixed 1.7.0, started production rollout.
