### ISSUE TITLE
Android app not loading 

### ISSUE THREAD

**Issue by Jabdullah81** [coolfiresolutions/core-service-desk#87]
ATTENTION: PLEASE DO NOT INCLUDE ANY PERSONALLY IDENTIFABLE INFORMATION (PII) WITHIN THIS REPORT. Please redact any PII from screenshots, videos or supporting media before attaching them to this report. Thank you.

**Describe the bug**
Pam with Ard is stating the android users when they pull up the app are only receiving a blue screen that spins.  They have tried to uninstall and reinstall the app but still having the same issues. 

**Where are you seeing this?**
Android

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Jabdullah81** [comment]
Android version 1.6.0

**Comment by cfsnkajok** [comment]
We are investigating. Thank you for the report.

**Comment by cfsbhawkins** [comment]
1.8.0 has been sent for approval, we removed map key retrieval and ToS checks on login.
