### ISSUE TITLE
New Android loading error 

### ISSUE THREAD

**Issue by Jabdullah81** [coolfiresolutions/core-service-desk#88]
ATTENTION: PLEASE DO NOT INCLUDE ANY PERSONALLY IDENTIFABLE INFORMATION (PII) WITHIN THIS REPORT. Please redact any PII from screenshots, videos or supporting media before attaching them to this report. Thank you.

**Describe the bug**
When driver is pulling up Core and trying to get into his sessions, he is just seeing a spinning circle.  Image attached below.  Marc said this is not the same issue as previously reported. 

**Where are you seeing this?**
Android app 1.7.0

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![185230695_491949915552872_408293452504482274_n](https://user-images.githubusercontent.com/80117952/117857970-ff95c580-b252-11eb-873b-66ff3f37f60f.png)

**Comment by cfsbhawkins** [comment]
Has someone checked the instance is not overloaded?

**Comment by cfsnkajok** [comment]
I don't see any instability on the client's workspace or logs. Jessie is able to login without an issue and I am able to pull up the workspace with no problem. We will keep an eye on this, but I don't believe this is a widespread issue at this point.
