### ISSUE TITLE
Android App Crashes On Open - V1.8

### ISSUE THREAD

**Issue by m-amarillas** [coolfiresolutions/core-service-desk#89]
ATTENTION: PLEASE DO NOT INCLUDE ANY PERSONALLY IDENTIFABLE INFORMATION (PII) WITHIN THIS REPORT. Please redact any PII from screenshots, videos or supporting media before attaching them to this report. Thank you.

**Describe the bug**
I'm running the 1.8 app on my Android phone and it is crashing when it tries to load my session dashboard. See video attached

**Where are you seeing this?**
Android v1.8 

**To Reproduce**
See video 

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/53492670/118139310-d6994000-b3cc-11eb-8fcf-96bc61a035a4.mp4

**Smartphone (please complete the following information):**
 - Android 1.8
 - Pixel 3a

**Comment by cfsbhawkins** [comment]
Manually update from Google Play, it was resolved in the latest version.
