### ISSUE TITLE
"Unexpected Errors" in Web App After SessionUpdate API Call

### ISSUE THREAD

**Issue by m-amarillas** [coolfiresolutions/core-service-desk#92]
ATTENTION: PLEASE DO NOT INCLUDE ANY PERSONALLY IDENTIFABLE INFORMATION (PII) WITHIN THIS REPORT. Please redact any PII from screenshots, videos or supporting media before attaching them to this report. Thank you.

**Describe the bug**
It appears that whenever there is a updateSession Mutation called via the API, the web app will start throwing errors. I'm not 100% certain of how to reproduce this everytime, but I see it pretty consistently and have had reports from Hogan and American Expediting. 

See the attached video for clarification on what I mean by Unexpected Errors

**Where are you seeing this?**
Web App

**To Reproduce**
1. Open a workspace
2. Put the workspace in the background (minimize the browser)
3. issue 1 to many updateSession API calls to Sessions
4. Go back to the workspace and try to navigate around

**Screenshots**

https://user-images.githubusercontent.com/53492670/118851026-f92ccc80-b896-11eb-8a12-e642206d6d83.mov

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
Let me know if I can provide any further insights. I confirmed that there are no GraphQL errors in the response, so it feels like a frontend issue.

**Comment by cfsnkajok** [comment]
@cfsadellamano , @stramel any thoughts on this?

**Comment by stramel** [comment]
Looks like everything in there is a result of not getting the connection for the notificationlist?

**Comment by m-amarillas** [comment]
Here's another screenshot when they click on the notifications bell.

![Screen Shot 2021-05-20 at 10 01 27 AM](https://user-images.githubusercontent.com/53492670/119008562-e62e0100-b957-11eb-8beb-138130033ea3.png)

**Comment by stramel** [comment]
Clicking the notification bell seems like it is a different issue? the `getValue` and missing connection seems related to the notification bell.

**Comment by m-amarillas** [comment]
It does feel like the error "Unable to find the NotificationList_notificationCenter connection" is thrown everytime this happens (from the screenshots I get). Not sure why that would effect the loading of Sessions or Filters, but it could be a by-product.

**Comment by m-amarillas** [comment]
I found out how to reproduce this issue. Follow these steps (video attached for reference):
1. Go to a Network with 50 or more Sessions
2. Open two windows
2. In the second window, scroll to the bottom of the list
3. Enter any of the bottom Sessions, Click Edit, and Save the Session
4. In the first window, try to filter/view sessions/view notifications. You will be presented with hard errors

This may seem like an edge case, but with the way our Hogan/AmEx/Acme integrations are setup, we are constantly updating Sessions that would be further down on the list, which is why we see this happening so much. 

Video:

https://user-images.githubusercontent.com/53492670/120232194-aa791e00-c218-11eb-8dc5-87ecade720f0.mov

**Comment by cfsadellamano** [comment]
This should now be resolved in version 2.10.0
